query OverlayGet($id: String) {
  overlays(id: $id) {
    carousel {
      id
      value
    }
    marathon {
      id
      value
      opts {
        disableWhenReachedZero
        showProgressGraph
        endTime
        maxEndTime
        showMilliseconds
        values {
          sub {
            tier1
            tier2
            tier3
          }
          resub {
            tier1
            tier2
            tier3
          }
          bits {
            addFraction
            bits
            time
          }
          tips {
            addFraction
            tips
            time
          }
        }
        marathonFont {
          family
          align
          color
          highlightcolor
          size
          weight
          borderColor
          borderPx
          shadow {
            shiftRight
            shiftDown
            blur
            opacity
            color
          }
        }
      }
    }
    stopwatch {
      id
      value
      opts {
        currentTime
        isPersistent
        isStartedOnSourceLoad
        showMilliseconds
        stopwatchFont {
          family
          align
          color
          highlightcolor
          size
          weight
          borderColor
          borderPx
          shadow {
            shiftRight
            shiftDown
            blur
            opacity
            color
          }
        }
      }
    }
    countdown {
      id
      value
      opts {
        time
        currentTime
        isPersistent
        isStartedOnSourceLoad
        messageWhenReachedZero
        showMessageWhenReachedZero
        showMilliseconds
        countdownFont {
          family
          align
          color
          highlightcolor
          size
          weight
          borderColor
          borderPx
          shadow {
            shiftRight
            shiftDown
            blur
            opacity
            color
          }
        }
        messageFont {
          family
          align
          color
          highlightcolor
          size
          weight
          borderColor
          borderPx
          shadow {
            shiftRight
            shiftDown
            blur
            opacity
            color
          }
        }
      }
    }
    credits {
      id
      value
      opts {
        social {
          type
          text
        }
        speed
        customTexts {
          type
          left
          middle
          right
        }
        clips {
          play
          period
          periodValue
          numOfClips
          volume
        }
        text {
          lastMessage
          lastSubMessage
          streamBy
          follow
          host
          raid
          cheer
          sub
          resub
          subgift
          subcommunitygift
          tip
        }
        show {
          follow
          host
          raid
          sub
          subgift
          subcommunitygift
          resub
          cheer
          clips
          tip
        }
      }
    }
    eventlist {
      id
      value
      opts {
        count
        ignore
        display
        order
      }
    }
    clips {
      id
      value
      opts {
        volume
        filter
        showLabel
      }
    }
    alerts {
      id
      value
      opts {
        galleryCache
        galleryCacheLimitInMb
      }
    }
    emotes {
      id
      value
      opts {
        emotesSize
        maxEmotesPerMessage
        animation
        animationTime
      }
    }
    emotescombo {
      id
      value
      opts {
        showEmoteInOverlayThreshold
        hideEmoteInOverlayAfter
      }
    }
    emotesfireworks {
      id
      value
      opts {
        emotesSize
        animationTime
        numOfEmotesPerExplosion
        numOfExplosions
      }
    }
    emotesexplode {
      id
      value
      opts {
        emotesSize
        animationTime
        numOfEmotes
      }
    }
    hypetrain {
      id
      value
    }
    clipscarousel {
      id
      value
      opts {
        customPeriod
        numOfClips
        volume
      }
    }
    tts {
      id
      value
      opts {
        voice
        volume
        rate
        pitch
        triggerTTSByHighlightedMessage
      }
    }
    polls {
      id
      value
      opts {
        theme
        hideAfterInactivity
        inactivityTime
        align
      }
    }
    obswebsocket {
      id
      value
      opts {
        allowedIPs
      }
    }
    group {
      id
      value
      opts {
        canvas {
          width
          height
        }
        items {
          id
          width
          height
          alignX
          alignY
          type
          opts
        }
      }
    }
  }
}